# Generated by Django 4.2.4 on 2023-10-11 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_cart_size_alter_orderplaced_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='size',
        ),
        migrations.RemoveField(
            model_name='orderplaced',
            name='size',
        ),
    ]
