# Generated by Django 4.2.4 on 2023-10-11 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_cart_size_remove_orderplaced_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='size',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='size',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
