# Generated by Django 4.2.4 on 2023-10-22 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_payment_alter_cart_user_alter_customer_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderplaced',
            name='payment',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
