# Generated by Django 4.2.4 on 2023-10-23 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_contact_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='user',
        ),
    ]
